export { default as Loader } from './Loader'
export { Loader2 as LoaderAlt } from './Loader'
export { default as AssetUploader } from './Upload'
export { default as Footer } from './Footer'
export { default as Sidenav } from './Admin/Sidenav'
export { default as Content } from './Admin/Content'
export { default as AddFood } from './Admin/AddFood'
export { default as Stats } from './Admin/Dashboard'
